language: c

sudo: false

os:
  - linux
  - osx

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update &&
      brew install qt &&
      brew install sdl;
    fi
  - if [ ! -f deps/bass24.zip ]; then
        mkdir -p deps && (
            cd deps &&
            wget http://www.un4seen.com/files/bass24-$TRAVIS_OS_NAME.zip -O bass24.zip
        )
    fi &&
    mkdir examples/include &&
    mkdir examples/lib &&
    unzip -d bass24 deps/bass24.zip &&
    cp bass24/bass.h examples/include/;
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cp bass24/libbass.dylib examples/lib/;
    fi;
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      cp bass24/x64/libbass.so examples/lib/;
    fi
  - if [ -n "$TRAVIS_TAG" ]; then
      export VERSION_TAG=${TRAVIS_TAG:1};
    else
      export VERSION_TAG=$TRAVIS_BRANCH;
    fi

script:
  - autoreconf -i &&
    mkdir build && (
      cd build &&
      ../configure --with-bass=`pwd`/../bass24 &&
      make
    )

cache:
  directories:
    - deps

addons:
  apt:
    packages:
      - libsdl1.2-dev

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      (cd editor &&
      macdeployqt editor.app &&
      zip -r rocket-editor-$VERSION_TAG-$TRAVIS_OS_NAME.zip editor.app)
    fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aCUNNh7Gevkxjjw6RE6xf1JpWPIHFrmmTGBsOgJ9J0hLDanxZRVZM0f4xgK3PArIFjL/9l3ollGlTjZuvkpiU7SieIpfbA5XJHwl/P1Kyw7lTu81e+CWttVDfL9r/x3JTT42lSM6ICLOJLuvZryrnNxRGTcntxebm7+g2vmh8nQ=
  file: editor/rocket-editor-$VERSION_TAG-$TRAVIS_OS_NAME.zip
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
